version: '3'

tasks:
  update:repo:
    desc: Update the Wiki repo
    vars:
      WIKI_REPO: ../lineage_wiki/
    cmds:
      - |
        cd {{.WIKI_REPO}}
        git pull

  extract:
    desc: Extract RDF from the Wiki
    env:
      LC_ALL: C
    cmds:
      - poetry run python extract.py

  update:
    desc: Update the Repository
    deps:
      - task: update:repo
    vars:
      MESSAGE: Update LineageOS Device Data
      EXPORT: lineage.nt
    cmds:
      - task: extract
      - |
        git add {{.EXPORT}}
        git commit -m "{{.MESSAGE}}"

  serve:fuseki:
    desc: Serve the model with a fuseki triple store
    docs: The model can be queries with SPARQL at http://localhost:3030/lineage/
    cmds:
      - docker run --rm -p 3030:3030 --name lineage_model -v .:/graph -d stain/jena-fuseki /jena-fuseki/fuseki-server --file=/graph/lineage.nt /lineage

  serve:quit:
    desc: Serve the model with a quit triple store
    docs: The model can be queries with SPARQL at http://localhost:5000/sparql
    cmds:
      - quit -t .
