version: '3'

vars:
  WIKI_REPO: ../lineage_wiki/
  WIKI_REPO_REMOTE: https://github.com/LineageOS/lineage_wiki

tasks:

  install:
    desc: Install the python dependencies
    cmds:
      - poetry install

  extract:
    desc: Extract RDF from the Wiki
    env:
      LC_ALL: C
    cmds:
      - poetry run python extract.py

  update:
    desc: Update the Repository
    deps:
      - task: repo:update
    vars:
      MESSAGE: Update LineageOS Device Data
      EXPORT: lineage.nt
    cmds:
      - task: extract
      - |
        git add {{.EXPORT}}
        git commit -m "{{.MESSAGE}}"

  serve:fuseki:
    desc: Serve the model with a fuseki triple store
    docs: The model can be queries with SPARQL at http://localhost:3030/lineage/
    cmds:
      - docker run --rm -p 3030:3030 --name lineage_model -v .:/graph -d stain/jena-fuseki /jena-fuseki/fuseki-server --file=/graph/lineage.nt /lineage

  serve:quit:
    desc: Serve the model with a quit triple store
    docs: The model can be queries with SPARQL at http://localhost:5000/sparql
    cmds:
      - quit -t .

  repo:init:
    desc: Initialize the wiki repository
    cmds:
      - |
        cd $(dirname "{{.WIKI_REPO}}")
        git clone {{.WIKI_REPO_REMOTE}}

  repo:update:
    desc: Update the Wiki repo
    cmds:
      - |
        cd {{.WIKI_REPO}}
        git pull
